#ifndef HASHTABLE_H
#define HASHTABLE_H

#include <stdio.h>
#include <math.h>
#include "DoubleListGeneric.h"
#include "Global.h"
#include "Section.h"

/**
 * @return a table of HASHLENGTH elements
 * @brief Create a table of HASHLENGTH elements.
 *
 */
LIST_DOUBLE* CreateHashTable();

/**
 * @param string char* to test.
 * @return int between 0 and HASHLENGTH
 * @brief Function of hash, generate an index between 0 and HASHLENGTH for the hash's table.
 *
 */
int Hash(char * string);

/**
 * @param hash LIST_DOUBLE** to update and SECTION* to test.
 * @brief Updating of hash's table with the new SECTION* at the index generated by the function Hash.
 * @return 1 if is not in it, return 0 if it is.
 */
int AddHashTable(LIST_DOUBLE **hash, SECTION *label);

/**
 * @param See if the string is in the LIST_DOUBLE **hash.
 * @brief Updating of hash's table with the new sting at the index generated by the function Hash.
 * @return the section's pointer if the string exist in the hash table, else NULL.
 */
SECTION* IsInHashTable(LIST_DOUBLE *hash, char* string);

/**
 * @param hashTable LIST_DOUBLE* to display.
 * @brief Display the hash's table thanks to the function display of the LIST_DOUBLE.
 *
 */
void DisplayHashTable(LIST_DOUBLE* hashTable);

/**
 * @param hash Pointer on the hashTable.
 * @brief Desallocate all elements of the hashTable.
 *
 */
void ErasedHashTable(LIST_DOUBLE** hash);

#endif
